# Generated by Django 4.1.5 on 2023-06-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_hesap'),
    ]

    operations = [
        migrations.AddField(
            model_name='hesap',
            name='sifre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
