# Generated by Django 4.1.5 on 2023-06-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_hesap_sifre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hesap',
            name='resim',
            field=models.ImageField(blank=True, upload_to='hesaplar/'),
        ),
    ]
